version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "hedge-mongo"
    ports:
      - 27017:27017
  hedgeness-app:
    image:  hedgeness-app:1.5
    container_name: hedgeness-app
    ports: 
      - 8084:8084
    links: 
     - hedge-mongo
     